<a href="https://colab.research.google.com/github/Imama-Kainat/ByteWise-MLDL/blob/main/Assign1Bit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Learning Material+Assignment
##List/Tupple/Set
https://www.google.com/url?q=https://www.youtube.com/watch?v%3DW8KRzm-HUcc&sa=D&source=editors&ust=1718044411454923&usg=AOvVaw2jbezX0psAdqfnyFfVNHhm

##Panda
https://www.google.com/url?q=https://www.youtube.com/watch?v%3DxECXZ3tyONo&sa=D&source=editors&ust=1718044411455147&usg=AOvVaw15pnu3Rv5cAzJaxBTmU4i0

##Assignment
https://www.google.com/url?q=https://docs.google.com/document/d/1Y52Wg10Zx3gQRwjTBT9-iIiJnNctEcZY/edit?usp%3Dsharing%26ouid%3D107689249093443406233%26rtpof%3Dtrue%26sd%3Dtrue&sa=D&source=editors&ust=1718044411455274&usg=AOvVaw2QiFLhN12XM5K6ZKN4wYJm


In [7]:
import numpy as np
basketplayer=[8.5,6,5.3,6.5,5.7]
type(basketplayer)
b_player=np.array(basketplayer)
b_player

array([8.5, 6. , 5.3, 6.5, 5.7])

# Baseball players' height
Create a numpy array from height_in. Name this new array np_height_in.
Print np_height_in.
Multiply np_height_in with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array, np_height_m.
Print out np_height_m and check if the output makes sense







In [8]:
height_in=[8.5,6,5.3,6.5,5.7]
np_height_in=np.array(height_in)
np_height_in

array([8.5, 6. , 5.3, 6.5, 5.7])

In [9]:
np_height_m=np_height_in*0.0254
np_height_m

array([0.2159 , 0.1524 , 0.13462, 0.1651 , 0.14478])

#Baseball player's BMI
The MLB also offers to let you analyze their weight data. Again, both are available as regular Python lists: height_in and weight_lb. height_in is in inches and weight_lb is in pounds.
It's now possible to calculate the BMI of each baseball player. Python code to convert height_in to a numpy array with the correct units is already available in the workspace. Follow the instructions step by step and finish the game! height_in and weight_lb are available as regular lists


1.   Create a numpy array from the weight_lb list with the correct units. Multiply by 0.453592 to go from pounds to kilograms. Store the resulting numpy array as np_weight_kg.
2. Use np_height_m and np_weight_kg to calculate the BMI of each player. 3. Use the following equation:BMI=weight(kg)height(m)2Save the resulting numpy array as bmi.
3. Print out bmi.


In [10]:
weight_lb =np.array([3,5,6,7,89])
np_weight_kg=0.453592*weight_lb
BMI=weight_lb*np_weight_kg
bmi=np.array(BMI)
BMI

array([   4.082328,   11.3398  ,   16.329312,   22.226008, 3592.902232])

#Lightweight baseball players
To subset both regular Python lists and numpy arrays, you can use square brackets:
x = [4 , 9 , 6, 3, 1]
x[1]
import numpy as np
y = np.array(x)
y[1]
For numpy specifically, you can also use boolean numpy arrays:
high = y > 5
y[high]
The code that calculates the BMI of all baseball players is already included. Follow the instructions and reveal interesting things from the data! height_in and weight_lb are available as regular lists.
##Instructions
Create a boolean numpy array: the element of the array should be True if the corresponding baseball player's BMI is below 21. You can use the < operator for this. Name the array light.
Print the array light.
Print out a numpy array with the BMIs of all baseball players whose BMI is below 21. Use light inside square brackets to do a selection on the bmi array

In [11]:
light=np.array(BMI<210)
light

array([ True,  True,  True,  True, False])

In [ ]:
bmi[light]

array([ 4.082328, 11.3398  , 16.329312, 22.226008])

#type coercion
numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.


In [12]:
np.array([True, 1, 2]) + np.array([3, 4, False]) #


array([4, 5, 2])

In [13]:
np.array([True, 1, 2, 3, 4, False])

array([1, 1, 2, 3, 4, 0])

In [14]:
np.array([4, 3, 0]) + np.array([0, 2, 2])


array([4, 5, 2])

In [15]:
np.array([1, 1, 2]) + np.array([3, 4, -1])


array([4, 5, 1])

In [16]:
np.array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

Convert heights and positions, which are regular lists, to numpy arrays. Call them np_heights and np_positions.
Extract all the heights of the goalkeepers. You can use a little trick here: use np_positions == 'GK' as an index for np_heights. Assign the result to gk_heights.
Extract all the heights of all the other players. This time use np_positions != 'GK' as an index for np_heights. Assign the result to other_heights.
Print out the median height of the goalkeepers using np.median(). Replace None with the correct code.
Do the same for the other players. Print out their median height. Replace None with the correct code.


positions=['GK', 'M', 'A', 'D']
np_positions=np.array(positions)
heights=[180, 215, 210, 210]
np_heights=np.array(heights)



In [17]:
positions=['GK', 'M', 'A', 'D']
heights=[180, 215, 210, 210]
np_heights =np.array(heights)
np_positions=np.array(positions)


In [18]:
gk_heights = np_heights[np_positions == 'GK']
other_heights=np_heights[np_positions!='GK']


In [19]:
median_gk_height = np.median(gk_heights)
print("Median height of goalkeepers:", median_gk_height)

#  Calculate and print median height of other players
median_other_height = np.median(other_heights)
print("Median height of other players:", median_other_height)


Median height of goalkeepers: 180.0
Median height of other players: 210.0
